#!/bin/bash -e


#
# Configuration
#
PYPI_NAME=STEME
DIR=www/STEME
RSYNC="rsync --verbose  --progress --stats --compress --recursive --times --perms --links"


#
# Update the options documentation
#
PYTHONPATH=python/:$PYTHONPATH \
    python python/scripts/create_options_docs >docs/source/options.rst


#
# Check everything is checked in
#
if ! git st | grep "working directory clean"
then
    git st
    echo "*************************************************************"
    echo "You need to check in everything before updating distribution."
    echo "*************************************************************"
    exit -1
fi


#
# Update the documentation and upload to pypi and our web host
#
pip install sphinx sphinx-pypi-upload
PYTHONPATH=python/:$PYTHONPATH python setup.py build_sphinx
PYTHONPATH=python/:$PYTHONPATH python setup.py upload_sphinx


#
# Upload source build to pypi
#
python setup.py sdist
twine upload --verbose -r pypi dist/*


#
# Remind user
#
echo "**************************************************************************"
echo "* Now is a good time to update the release number in the python package. *"
echo "**************************************************************************"
